data:
  # raw_data_path: "s3://your-bucket/raw_data.csv"
  processed_data_path: "../data/wave2vec_transcribed.csv"

models:
  transcription:
    wave_processor: "facebook/wav2vec2-base-960h"
    wave_model: "facebook/wav2vec2-base-960h"
    whisper_model: "medium"

  ner_model: "ner_custom_model"

  summarization: 
    sum_model: "facebook/bart-large-cnn"

  translation:
    model: "facebook/nllb-200-1.3B"
    src_lang: "eng_Latn"
    tgt_lang: "zho_Hans"


settings:
  use_gpu: true
  max_length_large: 300
  min_length_large: 100
  max_length_small: 100
  min_length_small: 50
  max_length_tiny: 30
  min_length_tiny: 10
